config/routes.rb
Rails.application.routes.draw do
  
  get 'chats/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'homes#top'
  get 'finder' => "finders#finder"
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end
  resources :diaries do
    resources :diary_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  attachment :profile_image

  has_many :diaries, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def self.get_by_word(search_word)
    where("name LIKE ?", "%#{search_word}%")
  end

  def self.get_by_sex(search_sex)
    where("sex = ?", "#{search_sex}")
  end

  def self.get_by_height(search_height)
    from = search_height.to_i - 2
    to = search_height.to_i + 2
    where(height: from..to)
  end

  def self.get_by_weight(search_weight)
    from = search_weight.to_i - 2
    to = search_weight.to_i + 2
    where(weight: from..to)
  end

  def self.get_by_target_weight(search_target_weight)
    from = search_target_weight.to_i - 2
    to = search_target_weight.to_i + 2
    where(target_weight: from..to)
  end

  def self.get_by_age(search_age)
    from_age = search_age.to_i - 2
    to_age = search_age.to_i + 2
    from_year = Date.today.strftime("%Y").to_i - to_age
    to_year = Date.today.strftime("%Y").to_i - from_age
    from = from_year.to_s
    to = to_year.to_s
    where(birthyear: from..to)
  end

  def self.get_by_style1(search_style)
    where("diet_style1 = ?", search_style)
  end

  def self.get_by_style2(search_style)
    where("diet_style2 = ?", search_style)
  end

  def self.get_by_style3(search_style)
    where("diet_style3 = ?", search_style)
  end

  def self.get_by_style4(search_style)
    where("diet_style4 = ?", search_style)
  end
  
  def limit_date(dates)
    if dates[0]  <　dates.last.prev_year
      @dates = dates.where(post_date)
    end
  end

  validates :name, length: { maximum: 10, minimum: 2 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do
      resource.update(confirmed_at: Time.now.utc) 
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.all.order(post_date: "ASC")
    @weights = @diaries.map(&:weight)
    @body_fat_percentages = @diaries.map(&:body_fat_percentage)
    @dates = @diaries.map{|diary| diary.post_date }
    if @dates[0] < @dates.last.prev_year
      @dates = @dates.select do |x|
        @dates.last.prev_year <= x
      end
      @weights = @weights.last(@dates.size)
      @body_fat_percentages = @body_fat_percentages.last(@dates.size)
    end
    @diary = Diary.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @diary = Diary.new
  end

end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/users/_graph.html.erb
<style>
  #chartdiv {
    width: 700px;
    height: 300px;
  }
</style>


<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script src="//www.amcharts.com/lib/4/lang/ja_JP.js"></script>

<script>
am4core.ready(function() {

am4core.useTheme(am4themes_animated);

var chart = am4core.create("chartdiv", am4charts.XYChart);
chart.dateFormatter.language = new am4core.Language();
chart.dateFormatter.language.locale = am4lang_ja_JP;
chart.language.locale["_date_day"] = "MMMdd日";
chart.language.locale["_date_year"] = "yyyy年";

const weights = <%== JSON.dump(@weights) %>;
const body_fat_percentages = <%== JSON.dump(@body_fat_percentages) %>;
const dates = <%== JSON.dump(@dates) %>;

var firstDate = new Date(dates[0])
var lastDate = new Date(dates.slice(-1)[0])
var termDate = (lastDate - firstDate) / 1000 / 60 / 60 / 24 + 1

function generateChartData() {
  var chartData = [];
  for (var j = 0; j < weights.length; j++ ) {
    for (var i = 0; i < termDate; i++ ) {
      var newDate = new Date(firstDate)
      newDate.setDate(newDate.getDate() + i);
      if ((new Date(dates[j])) - (newDate) == 0 ){
        weight = weights[j]
        body_fat_percentage = body_fat_percentages[j]
        chartData.push({
          date1: newDate,
          weight: weight,
          date2: newDate,
          body_fat_percentage: body_fat_percentage
        });
      }
    }
  }
  return chartData;
}

chart.data = generateChartData();

//グラフタイトルの設定
var title = chart.titles.create();
title.text = "スクロールバーで表示範囲を変更できます"; //グラフタイトルの設定
title.fontSize = 15; //グラフタイトルのフォントサイズの設定

//第１横軸の設定
var dateAxis = chart.xAxes.push(new am4charts.DateAxis());
dateAxis.renderer.grid.template.location = 0;
dateAxis.renderer.labels.template.fill = am4core.color("#ffffff");

//第２横軸の設定
var dateAxis2 = chart.xAxes.push(new am4charts.DateAxis());
dateAxis2.tooltip.disabled = true; //Tooltipの非表示設定
dateAxis2.renderer.grid.template.location = 0;
dateAxis2.renderer.labels.template.fill = am4core.color("#000000");

//第１縦軸の設定
var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.tooltip.disabled = true;
valueAxis.renderer.labels.template.fill = am4core.color("#e59165");
valueAxis.renderer.minWidth = 60;
valueAxis.renderer.labels.template.adapter.add("text", function(text) {
  return text + "kg";
});
valueAxis.renderer.fontWeight = "bold"; //軸の値を太字に変更

//第２縦軸の設定
var valueAxis2 = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis2.tooltip.disabled = true;
valueAxis2.renderer.grid.template.strokeDasharray = "2,3";
valueAxis2.renderer.labels.template.fill = am4core.color("#dfcc64");
valueAxis2.renderer.minWidth = 60;
valueAxis2.renderer.labels.template.adapter.add("text", function(text) {
  return text + "%";
});
valueAxis2.renderer.opposite = true; //第２縦軸を右側に設定
valueAxis2.renderer.fontWeight = "bold"; //軸の値を太字に変更

//第１縦軸用の値の設定
var series = chart.series.push(new am4charts.LineSeries());
series.name = "体重";
series.dataFields.dateX = "date1";
series.dataFields.valueY = "weight";
series.tooltipText = "{valueY.value}kg";
series.fill = am4core.color("#e59165");
series.stroke = am4core.color("#e59165");
series.smoothing = "monotoneX";
series.strokeWidth = 2;
series.minBulletDistance = 15;

//系列のポイントの設定(第１縦軸)
var bullet = series.bullets.push(new am4charts.Bullet());
var circle = bullet.createChild(am4core.Circle);
circle.width = 5;
circle.height = 5;
circle.horizontalCenter = "middle";
circle.verticalCenter = "middle";

//第１縦軸用の値の設定
var series2 = chart.series.push(new am4charts.LineSeries());
series2.name = "体脂肪率";
series2.dataFields.dateX = "date2";
series2.dataFields.valueY = "body_fat_percentage";
series2.yAxis = valueAxis2;
series2.xAxis = dateAxis2;
series2.tooltipText = "{valueY.value}%"; //ツールチップの表示設定
series2.fill = am4core.color("#dfcc64"); //ツールチップの色
series2.stroke = am4core.color("#dfcc64"); //グラフの線の色
series2.smoothing = "monotoneX";
series2.strokeWidth = 2;
series2.minBulletDistance = 15;

//系列のポイントの設定(第2縦軸)
var bullet2 = series2.bullets.push(new am4charts.Bullet());
var circle2 = bullet2.createChild(am4core.Circle);
circle2.width = 5;
circle2.height = 5;
circle2.horizontalCenter = "middle";
circle2.verticalCenter = "middle";

chart.scrollbarX = new am4core.Scrollbar(); //スクロールバーの設定

//カーソルの設定
chart.cursor = new am4charts.XYCursor();
chart.cursor.xAxis = dateAxis2;

//凡例の設定
chart.legend = new am4charts.Legend();
chart.legend.parent = chart.plotContainer;
chart.legend.zIndex = 100;
chart.legend.position = "top";
chart.legend.contentAlign = "right";


chart.events.on("ready", function () {
  dateAxis.zoom({start:1-30/termDate, end:1});
  dateAxis2.zoom({start:1-30/termDate, end:1});
});

//グリッド線の設定
valueAxis2.renderer.grid.template.strokeOpacity = 0.07;
dateAxis2.renderer.grid.template.strokeOpacity = 0;
dateAxis.renderer.grid.template.strokeOpacity = 0;
valueAxis.renderer.grid.template.strokeOpacity = 0.07;

});
</script>

<div id="chartdiv"></div>

app/views/users/_index.html.haml
%table.table
  %thead
    %tr
      %th image
      %th name
      %th{:colspan => "4"}
  %tbody
    - users.each do |user|
      %tr.table_link
        %td{"data-link": "/users/#{user.id}"}
          = attachment_image_tag(user, :profile_image, size: "30x30", fallback: "l_e_others_500.jpg")
        %td{"data-link": "/users/#{user.id}"}
          = link_to user.name
        %td{"data-link": "/users/#{user.id}"}
          フォロー数:
          %span{:id => "followings_count_#{user.id}"}
            #{user.followings.count}
        %td{"data-link": "/users/#{user.id}"}
          フォロワー数:
          %span{:id => "followers_count_#{user.id}"}
            #{user.followers.count}
        -if user_signed_in?
          %td
            - if current_user != user
              %span{:id => "follow_bottons_#{user.id}"}
                = render "relationships/follow_form", user: user
= paginate users

app/views/users/_info.html.haml
%table.table
  %tr= attachment_image_tag(user, :profile_image, size: "20x20", fallback: "l_e_others_500.jpg")
  %tr
    %th name
    %th= user.name

  %tr
    %th フォロー中
    %th
      = link_to followings_user_path(user) do
        %span.followings_count
          = user.followings.count
  %tr
    %th フォロワー
    %th
      = link_to followers_user_path(user) do
        %span.followers_count
          = user.followers.count
- if current_user == user
  = link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}"
- else
  = link_to "チャット", chat_path(user.id)
  %div{:id => "follow_bottons_#{user.id}"}
    = render "relationships/follow_form", user: user

app/views/users/edit.html.haml
%h1 ユーザープロフィール設定
= form_with model:@user, local:true do |f|
  .field
    = f.label :name
    = f.text_field :name, placeholder:"名前"
  .field
    = f.label :sex
    = f.radio_button :gender, "男性"
    男性 #{f.radio_button :gender, "女性"}女性

app/views/users/index.html.haml
.container.px-5.px-sm-0
  .row
    - if user_signed_in?
      .col-md-3
        
        %h3.mt-3 体重を記録する
        = render 'diaries/form', diary: @diary
    .col-md-9
      %h2 Users
      = render 'index',users: @users
    

app/views/users/show.html.haml
.container.px-5.px-sm-0
  .row
    .col-md-3
      %h2.mt-3 体重を記録する
      = render "diaries/form", diary: @diary
      %h2 User info
      = render "info", user: @user
    .col-md-8.offset-md-1
      %h2　記録
      = render "graph"
      = render "diaries/index",diaries: @diaries