config/routes.rb
Rails.application.routes.draw do
  
  get 'chats/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'homes#top'
  get 'finder' => "finders#finder"
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end
  resources :diaries do
    resources :diary_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/models/diary.rb
class Diary < ApplicationRecord
  
  belongs_to :user
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :image1
  attachment :image2
  attachment :image3
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(word)
    @diaries = Diary.where("title LIKE ?", "%#{word}%")
  end
  
end

app/models/diary_comment.rb
class DiaryComment < ApplicationRecord

  belongs_to :diary
  belongs_to :user

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :diary
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :chats
  has_many :user_rooms
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  attachment :profile_image

  has_many :diaries, dependent: :destroy
  has_many :diary_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def following?(user)
    followings.include?(user)
  end

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def self.get_by_word(search_word)
    where("name LIKE ?", "%#{search_word}%")
  end

  def self.get_by_sex(search_sex)
    where("sex = ?", "#{search_sex}")
  end

  def self.get_by_height(search_height)
    from = search_height.to_i - 2
    to = search_height.to_i + 2
    where(height: from..to)
  end

  def self.get_by_weight(search_weight)
    from = search_weight.to_i - 2
    to = search_weight.to_i + 2
    where(weight: from..to)
  end

  def self.get_by_target_weight(search_target_weight)
    from = search_target_weight.to_i - 2
    to = search_target_weight.to_i + 2
    where(target_weight: from..to)
  end

  def self.get_by_age(search_age)
    from_age = search_age.to_i - 2
    to_age = search_age.to_i + 2
    from_year = Date.today.strftime("%Y").to_i - to_age
    to_year = Date.today.strftime("%Y").to_i - from_age
    from = from_year.to_s
    to = to_year.to_s
    where(birthyear: from..to)
  end

  def self.get_by_style1(search_style)
    where("diet_style1 = ?", search_style)
  end

  def self.get_by_style2(search_style)
    where("diet_style2 = ?", search_style)
  end

  def self.get_by_style3(search_style)
    where("diet_style3 = ?", search_style)
  end

  def self.get_by_style4(search_style)
    where("diet_style4 = ?", search_style)
  end
  
  def limit_date(dates)
    if dates[0]  <　dates.last.prev_year
      @dates = dates.where(post_date)
    end
  end

  validates :name, length: { maximum: 10, minimum: 2 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end
  
  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.all.order(post_date: "ASC")
    @weights = @diaries.map(&:weight)
    @body_fat_percentages = @diaries.map(&:body_fat_percentage)
    @dates = @diaries.map{|diary| diary.post_date }
    if @dates[0] < @dates.last.prev_year
      @dates = @dates.select do |x|
        @dates.last.prev_year <= x
      end
      @weights = @weights.last(@dates.size)
      @body_fat_percentages = @body_fat_percentages.last(@dates.size)
    end
    @diary = Diary.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @diary = Diary.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dieter
    = csrf_meta_tags
    = csp_meta_tag
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  %body
    %header
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-danger
        .container
          %a.navbar-brand{:href => "/"}
            %span Dieter
          %ul.navbar-nav.ml-auto
          %button{class: "navbar-toggler", type: "button", "data-toggle": "collapse", "data-target": "#navbarNavDropdown", "aria-controls": "navbarNavDropdown", "aria-expanded": "false", "aria-label": "Toggle navigation"}
            %span.navbar-toggler-icon
          #navbarNavDropdown.collapse.navbar-collapse
            %ul.navbar-nav.ml-auto
              - if user_signed_in?
                %li= link_to " home", user_path(current_user), class: "fas fa-home nav-link text-light"
                %li= link_to " users", users_path, class: "fas fa-users nav-link text-light"
                %li= link_to " Diaries", diaries_path , class: "fas fa-book-open nav-link text-light"
                %li= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light"
              - else
                %li= link_to " Home", root_path,class: "fas fa-home nav-link text-light"
                %li= link_to " users", users_path, class: "fas fa-users nav-link text-light"
                %li= link_to " Diaries", diaries_path , class: "fas fa-book-open nav-link text-light"
                %li= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light"
                %li= link_to " login", new_user_session_path , class: "fas fa-sign-in-alt nav-link text-light"
            .search
            = form_with url: finder_path, method: :get, local: :true do |f|
              = f.search_field :word
              = f.submit "検索"
    %main
      %p.notice
        = notice
      %p.alert
        = alert
      = yield
      
    %footer
      .container.mt-5
        .row
          .mx-auto
            %p CopyRight Infratop.inc